/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmisionesRouteImport } from './routes/admisiones'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CentroControlRouteImport } from './routes/centro-control'
import { Route as ComunicacionesRouteImport } from './routes/comunicaciones'
import { Route as ConcurrentesRouteImport } from './routes/concurrentes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as CronogramaRouteImport } from './routes/cronograma'
import { Route as DocumentacionRouteImport } from './routes/documentacion'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as FichaMaestraRouteImport } from './routes/ficha-maestra'
import { Route as FirmasRouteImport } from './routes/firmas'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as PlanillasRouteImport } from './routes/planillas'
import { Route as PrestacionesRouteImport } from './routes/prestaciones'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as SecretariaRouteImport } from './routes/secretaria'
import { Route as TransporteRouteImport } from './routes/transporte'
import { Route as TurneroRouteImport } from './routes/turnero'
import { Route as ViandasRouteImport } from './routes/viandas'
import { Route as Vista360RouteImport } from './routes/vista-360'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmisionesRoute = AdmisionesRouteImport.update({
  id: '/admisiones',
  path: '/admisiones',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CentroControlRoute = CentroControlRouteImport.update({
  id: '/centro-control',
  path: '/centro-control',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunicacionesRoute = ComunicacionesRouteImport.update({
  id: '/comunicaciones',
  path: '/comunicaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrentesRoute = ConcurrentesRouteImport.update({
  id: '/concurrentes',
  path: '/concurrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const CronogramaRoute = CronogramaRouteImport.update({
  id: '/cronograma',
  path: '/cronograma',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
  id: '/documentacion',
  path: '/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FichaMaestraRoute = FichaMaestraRouteImport.update({
  id: '/ficha-maestra',
  path: '/ficha-maestra',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmasRoute = FirmasRouteImport.update({
  id: '/firmas',
  path: '/firmas',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanillasRoute = PlanillasRouteImport.update({
  id: '/planillas',
  path: '/planillas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestacionesRoute = PrestacionesRouteImport.update({
  id: '/prestaciones',
  path: '/prestaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const SecretariaRoute = SecretariaRouteImport.update({
  id: '/secretaria',
  path: '/secretaria',
  getParentRoute: () => rootRouteImport,
} as any)
const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneroRoute = TurneroRouteImport.update({
  id: '/turnero',
  path: '/turnero',
  getParentRoute: () => rootRouteImport,
} as any)
const ViandasRoute = ViandasRouteImport.update({
  id: '/viandas',
  path: '/viandas',
  getParentRoute: () => rootRouteImport,
} as any)
const Vista360Route = Vista360RouteImport.update({
  id: '/vista-360',
  path: '/vista-360',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admisiones': typeof AdmisionesRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/centro-control': typeof CentroControlRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cronograma': typeof CronogramaRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/ficha-maestra': typeof FichaMaestraRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/planillas': typeof PlanillasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/secretaria': typeof SecretariaRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
  '/vista-360': typeof Vista360Route
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admisiones': typeof AdmisionesRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/centro-control': typeof CentroControlRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cronograma': typeof CronogramaRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/ficha-maestra': typeof FichaMaestraRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/planillas': typeof PlanillasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/secretaria': typeof SecretariaRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
  '/vista-360': typeof Vista360Route
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admisiones': typeof AdmisionesRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/centro-control': typeof CentroControlRoute
  '/comunicaciones': typeof ComunicacionesRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/cronograma': typeof CronogramaRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/ficha-maestra': typeof FichaMaestraRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/planillas': typeof PlanillasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/secretaria': typeof SecretariaRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
  '/vista-360': typeof Vista360Route
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admisiones'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/centro-control'
    | '/comunicaciones'
    | '/concurrentes'
    | '/configuracion'
    | '/cronograma'
    | '/documentacion'
    | '/facturacion'
    | '/ficha-maestra'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/planillas'
    | '/prestaciones'
    | '/reportes'
    | '/secretaria'
    | '/transporte'
    | '/turnero'
    | '/viandas'
    | '/vista-360'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admisiones'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/centro-control'
    | '/comunicaciones'
    | '/concurrentes'
    | '/configuracion'
    | '/cronograma'
    | '/documentacion'
    | '/facturacion'
    | '/ficha-maestra'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/planillas'
    | '/prestaciones'
    | '/reportes'
    | '/secretaria'
    | '/transporte'
    | '/turnero'
    | '/viandas'
    | '/vista-360'
  id:
    | '__root__'
    | '/'
    | '/admisiones'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/centro-control'
    | '/comunicaciones'
    | '/concurrentes'
    | '/configuracion'
    | '/cronograma'
    | '/documentacion'
    | '/facturacion'
    | '/ficha-maestra'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/planillas'
    | '/prestaciones'
    | '/reportes'
    | '/secretaria'
    | '/transporte'
    | '/turnero'
    | '/viandas'
    | '/vista-360'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmisionesRoute: typeof AdmisionesRoute
  AlertasRoute: typeof AlertasRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  CentroControlRoute: typeof CentroControlRoute
  ComunicacionesRoute: typeof ComunicacionesRoute
  ConcurrentesRoute: typeof ConcurrentesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  CronogramaRoute: typeof CronogramaRoute
  DocumentacionRoute: typeof DocumentacionRoute
  FacturacionRoute: typeof FacturacionRoute
  FichaMaestraRoute: typeof FichaMaestraRoute
  FirmasRoute: typeof FirmasRoute
  LotesRoute: typeof LotesRoute
  NotasRoute: typeof NotasRoute
  PlanillasRoute: typeof PlanillasRoute
  PrestacionesRoute: typeof PrestacionesRoute
  ReportesRoute: typeof ReportesRoute
  SecretariaRoute: typeof SecretariaRoute
  TransporteRoute: typeof TransporteRoute
  TurneroRoute: typeof TurneroRoute
  ViandasRoute: typeof ViandasRoute
  Vista360Route: typeof Vista360Route
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admisiones': {
      id: '/admisiones'
      path: '/admisiones'
      fullPath: '/admisiones'
      preLoaderRoute: typeof AdmisionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/centro-control': {
      id: '/centro-control'
      path: '/centro-control'
      fullPath: '/centro-control'
      preLoaderRoute: typeof CentroControlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunicaciones': {
      id: '/comunicaciones'
      path: '/comunicaciones'
      fullPath: '/comunicaciones'
      preLoaderRoute: typeof ComunicacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrentes': {
      id: '/concurrentes'
      path: '/concurrentes'
      fullPath: '/concurrentes'
      preLoaderRoute: typeof ConcurrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cronograma': {
      id: '/cronograma'
      path: '/cronograma'
      fullPath: '/cronograma'
      preLoaderRoute: typeof CronogramaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacion': {
      id: '/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof DocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ficha-maestra': {
      id: '/ficha-maestra'
      path: '/ficha-maestra'
      fullPath: '/ficha-maestra'
      preLoaderRoute: typeof FichaMaestraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmas': {
      id: '/firmas'
      path: '/firmas'
      fullPath: '/firmas'
      preLoaderRoute: typeof FirmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planillas': {
      id: '/planillas'
      path: '/planillas'
      fullPath: '/planillas'
      preLoaderRoute: typeof PlanillasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestaciones': {
      id: '/prestaciones'
      path: '/prestaciones'
      fullPath: '/prestaciones'
      preLoaderRoute: typeof PrestacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/secretaria': {
      id: '/secretaria'
      path: '/secretaria'
      fullPath: '/secretaria'
      preLoaderRoute: typeof SecretariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnero': {
      id: '/turnero'
      path: '/turnero'
      fullPath: '/turnero'
      preLoaderRoute: typeof TurneroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viandas': {
      id: '/viandas'
      path: '/viandas'
      fullPath: '/viandas'
      preLoaderRoute: typeof ViandasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vista-360': {
      id: '/vista-360'
      path: '/vista-360'
      fullPath: '/vista-360'
      preLoaderRoute: typeof Vista360RouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmisionesRoute: AdmisionesRoute,
  AlertasRoute: AlertasRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  CentroControlRoute: CentroControlRoute,
  ComunicacionesRoute: ComunicacionesRoute,
  ConcurrentesRoute: ConcurrentesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  CronogramaRoute: CronogramaRoute,
  DocumentacionRoute: DocumentacionRoute,
  FacturacionRoute: FacturacionRoute,
  FichaMaestraRoute: FichaMaestraRoute,
  FirmasRoute: FirmasRoute,
  LotesRoute: LotesRoute,
  NotasRoute: NotasRoute,
  PlanillasRoute: PlanillasRoute,
  PrestacionesRoute: PrestacionesRoute,
  ReportesRoute: ReportesRoute,
  SecretariaRoute: SecretariaRoute,
  TransporteRoute: TransporteRoute,
  TurneroRoute: TurneroRoute,
  ViandasRoute: ViandasRoute,
  Vista360Route: Vista360Route,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
