/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertasRouteImport } from './routes/alertas'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConcurrentesRouteImport } from './routes/concurrentes'
import { Route as ConfiguracionRouteImport } from './routes/configuracion'
import { Route as DocumentacionRouteImport } from './routes/documentacion'
import { Route as FacturacionRouteImport } from './routes/facturacion'
import { Route as FirmasRouteImport } from './routes/firmas'
import { Route as LotesRouteImport } from './routes/lotes'
import { Route as NotasRouteImport } from './routes/notas'
import { Route as PrestacionesRouteImport } from './routes/prestaciones'
import { Route as ReportesRouteImport } from './routes/reportes'
import { Route as TransporteRouteImport } from './routes/transporte'
import { Route as TurneroRouteImport } from './routes/turnero'
import { Route as ViandasRouteImport } from './routes/viandas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertasRoute = AlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrentesRoute = ConcurrentesRouteImport.update({
  id: '/concurrentes',
  path: '/concurrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfiguracionRoute = ConfiguracionRouteImport.update({
  id: '/configuracion',
  path: '/configuracion',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentacionRoute = DocumentacionRouteImport.update({
  id: '/documentacion',
  path: '/documentacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FacturacionRoute = FacturacionRouteImport.update({
  id: '/facturacion',
  path: '/facturacion',
  getParentRoute: () => rootRouteImport,
} as any)
const FirmasRoute = FirmasRouteImport.update({
  id: '/firmas',
  path: '/firmas',
  getParentRoute: () => rootRouteImport,
} as any)
const LotesRoute = LotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => rootRouteImport,
} as any)
const NotasRoute = NotasRouteImport.update({
  id: '/notas',
  path: '/notas',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestacionesRoute = PrestacionesRouteImport.update({
  id: '/prestaciones',
  path: '/prestaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportesRoute = ReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => rootRouteImport,
} as any)
const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)
const TurneroRoute = TurneroRouteImport.update({
  id: '/turnero',
  path: '/turnero',
  getParentRoute: () => rootRouteImport,
} as any)
const ViandasRoute = ViandasRouteImport.update({
  id: '/viandas',
  path: '/viandas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alertas': typeof AlertasRoute
  '/auth': typeof AuthRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/configuracion': typeof ConfiguracionRoute
  '/documentacion': typeof DocumentacionRoute
  '/facturacion': typeof FacturacionRoute
  '/firmas': typeof FirmasRoute
  '/lotes': typeof LotesRoute
  '/notas': typeof NotasRoute
  '/prestaciones': typeof PrestacionesRoute
  '/reportes': typeof ReportesRoute
  '/transporte': typeof TransporteRoute
  '/turnero': typeof TurneroRoute
  '/viandas': typeof ViandasRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/concurrentes'
    | '/configuracion'
    | '/documentacion'
    | '/facturacion'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/prestaciones'
    | '/reportes'
    | '/transporte'
    | '/turnero'
    | '/viandas'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/concurrentes'
    | '/configuracion'
    | '/documentacion'
    | '/facturacion'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/prestaciones'
    | '/reportes'
    | '/transporte'
    | '/turnero'
    | '/viandas'
  id:
    | '__root__'
    | '/'
    | '/alertas'
    | '/auth'
    | '/calendario'
    | '/concurrentes'
    | '/configuracion'
    | '/documentacion'
    | '/facturacion'
    | '/firmas'
    | '/lotes'
    | '/notas'
    | '/prestaciones'
    | '/reportes'
    | '/transporte'
    | '/turnero'
    | '/viandas'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertasRoute: typeof AlertasRoute
  AuthRoute: typeof AuthRoute
  CalendarioRoute: typeof CalendarioRoute
  ConcurrentesRoute: typeof ConcurrentesRoute
  ConfiguracionRoute: typeof ConfiguracionRoute
  DocumentacionRoute: typeof DocumentacionRoute
  FacturacionRoute: typeof FacturacionRoute
  FirmasRoute: typeof FirmasRoute
  LotesRoute: typeof LotesRoute
  NotasRoute: typeof NotasRoute
  PrestacionesRoute: typeof PrestacionesRoute
  ReportesRoute: typeof ReportesRoute
  TransporteRoute: typeof TransporteRoute
  TurneroRoute: typeof TurneroRoute
  ViandasRoute: typeof ViandasRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alertas': {
      id: '/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AlertasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrentes': {
      id: '/concurrentes'
      path: '/concurrentes'
      fullPath: '/concurrentes'
      preLoaderRoute: typeof ConcurrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configuracion': {
      id: '/configuracion'
      path: '/configuracion'
      fullPath: '/configuracion'
      preLoaderRoute: typeof ConfiguracionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documentacion': {
      id: '/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof DocumentacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facturacion': {
      id: '/facturacion'
      path: '/facturacion'
      fullPath: '/facturacion'
      preLoaderRoute: typeof FacturacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/firmas': {
      id: '/firmas'
      path: '/firmas'
      fullPath: '/firmas'
      preLoaderRoute: typeof FirmasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lotes': {
      id: '/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notas': {
      id: '/notas'
      path: '/notas'
      fullPath: '/notas'
      preLoaderRoute: typeof NotasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestaciones': {
      id: '/prestaciones'
      path: '/prestaciones'
      fullPath: '/prestaciones'
      preLoaderRoute: typeof PrestacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reportes': {
      id: '/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof ReportesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/turnero': {
      id: '/turnero'
      path: '/turnero'
      fullPath: '/turnero'
      preLoaderRoute: typeof TurneroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viandas': {
      id: '/viandas'
      path: '/viandas'
      fullPath: '/viandas'
      preLoaderRoute: typeof ViandasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertasRoute: AlertasRoute,
  AuthRoute: AuthRoute,
  CalendarioRoute: CalendarioRoute,
  ConcurrentesRoute: ConcurrentesRoute,
  ConfiguracionRoute: ConfiguracionRoute,
  DocumentacionRoute: DocumentacionRoute,
  FacturacionRoute: FacturacionRoute,
  FirmasRoute: FirmasRoute,
  LotesRoute: LotesRoute,
  NotasRoute: NotasRoute,
  PrestacionesRoute: PrestacionesRoute,
  ReportesRoute: ReportesRoute,
  TransporteRoute: TransporteRoute,
  TurneroRoute: TurneroRoute,
  ViandasRoute: ViandasRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
