/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ConcurrentesRouteImport } from './routes/concurrentes'
import { Route as PrestacionesRouteImport } from './routes/prestaciones'
import { Route as TransporteRouteImport } from './routes/transporte'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ConcurrentesRoute = ConcurrentesRouteImport.update({
  id: '/concurrentes',
  path: '/concurrentes',
  getParentRoute: () => rootRouteImport,
} as any)
const PrestacionesRoute = PrestacionesRouteImport.update({
  id: '/prestaciones',
  path: '/prestaciones',
  getParentRoute: () => rootRouteImport,
} as any)
const TransporteRoute = TransporteRouteImport.update({
  id: '/transporte',
  path: '/transporte',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/prestaciones': typeof PrestacionesRoute
  '/transporte': typeof TransporteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/prestaciones': typeof PrestacionesRoute
  '/transporte': typeof TransporteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/concurrentes': typeof ConcurrentesRoute
  '/prestaciones': typeof PrestacionesRoute
  '/transporte': typeof TransporteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/calendario' | '/concurrentes' | '/prestaciones' | '/transporte'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/calendario' | '/concurrentes' | '/prestaciones' | '/transporte'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/concurrentes'
    | '/prestaciones'
    | '/transporte'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ConcurrentesRoute: typeof ConcurrentesRoute
  PrestacionesRoute: typeof PrestacionesRoute
  TransporteRoute: typeof TransporteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/concurrentes': {
      id: '/concurrentes'
      path: '/concurrentes'
      fullPath: '/concurrentes'
      preLoaderRoute: typeof ConcurrentesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prestaciones': {
      id: '/prestaciones'
      path: '/prestaciones'
      fullPath: '/prestaciones'
      preLoaderRoute: typeof PrestacionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transporte': {
      id: '/transporte'
      path: '/transporte'
      fullPath: '/transporte'
      preLoaderRoute: typeof TransporteRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ConcurrentesRoute: ConcurrentesRoute,
  PrestacionesRoute: PrestacionesRoute,
  TransporteRoute: TransporteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
